### ISSUE TITLE
Non installation fix & possible script error on test?

### ISSUE THREAD

**Issue by GodSiPhur** [cm45t3r/candlestick#1]
Let me start by saying that this is exactly what I had been looking for, and was quite surprised that there weren't more projects of this type on here.

Okay now the issue(s)
1. Easy fix . . . following download and running install, install was rejected due to the project name being the same as one the dependencies in the Package.Json file. - fixed by Capitalising the name of the project in this file and running npm install Candlestick instead of candlestick.

2. Issue on test (which I'm not going to need, but ran anyway) throwing up 

> mocha --check-leaks --use_strict

 error. May be something in the script?

**Comment by cm45t3r** [comment]
@GodSiPhur thanks for pointing it out. I will check why install and test fail and notify these can be local issues.

**Comment by cm45t3r** [comment]
Fixed by 56d87eb245bc81771f2ca4efc3dd12860dec887f
