### ISSUE TITLE
isEngulfed function

### ISSUE THREAD

**Issue by GmiSoft** [cm45t3r/candlestick#3]
First of all, thank's for sharing this code.
I'm not a python developer but I think there's an issue with isEngulfed function.

Shortest candlestick is engulfed by a longest if the body of longest which completely overlaps or engulfs the body of the shortest

1. Math.max(shortest.open, shortest.close) < Math.max(longest .open, longest .close)
2. Math.min(shortest.open, shortest.close) > Math.min(longest .open, longest .close)

if this two conditions are true so bodyLen(shortest) < bodyLen(longest)

Thank's

**Comment by cm45t3r** [comment]
Hi @GmiSoft,

Are you asking if `isEngulfed` should include the case when `bodyLen(shortest) === bodyLen(longest)`?

**Comment by cm45t3r** [comment]
Hi @GmiSoft ,

Thank you for reporting this issue. I fixed this with commit 9bfbfe255c39f3d7531fa9eea928e3fd7d29fb81. Please let me know if it works and looks in good shape.

Thanks.
