### ISSUE TITLE
Merge Conflicts in Your Package.json

### ISSUE THREAD

**Issue by manufacturedba** [cm45t3r/candlestick#5]
Had issues installing directly from trunk.  Saw you had some leftovers from a merge

```
<<<<<<< HEAD
=======
```

**Comment by cm45t3r** [comment]
Hi @manufacturedba thanks for reporting.

**Comment by cm45t3r** [comment]
Fixed by 56d87eb245bc81771f2ca4efc3dd12860dec887f
